[package]
name = "abc307"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
competitive = { git = "https://github.com/tanakh/competitive-rs.git" }
proconio = "*"
typenum = "*"
